### PR TITLE
Feature update

### PR DESCRIPTION
**Pull request by shashikant-ghangare**
Added support for Pytorch 1.0 by following changes:
- Changed the sub-module Precise ROI Pooling branch to master for Pytorch 1.0 support.
- Updated installation instructions for Pytorch 1.0 using conda.
- Update instructions to compile Precise ROI Pooling.

### CODE REVIEW

**Comment by martin-danelljan** [comment]
Hi. Nice work. But, for me it seems to be a problem to load the model. Did you have any such problems?

Here is the detailed error:

```
Traceback (most recent call last):
  File "run_webcam.py", line 35, in <module>
    main()
  File "run_webcam.py", line 31, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug)
  File "run_webcam.py", line 20, in run_webcam
    tracker.run_webcam(debug)
  File "../pytracking/evaluation/tracker.py", line 94, in run_webcam
    tracker.track_webcam()
  File "../pytracking/tracker/base/basetracker.py", line 179, in track_webcam
    self.initialize_features()
  File "../pytracking/tracker/atom/atom.py", line 19, in initialize_features
    self.params.features.initialize()
  File "../pytracking/features/extractor.py", line 16, in initialize
    f.initialize()
  File "../pytracking/features/deep.py", line 95, in initialize
    self.net, _ = load_network(net_path_full, backbone_pretrained=False)
  File "../ltr/admin/loading.py", line 53, in load_network
    checkpoint_dict = torch_load_legacy(checkpoint_path)
  File "../ltr/admin/loading.py", line 97, in torch_load_legacy
    checkpoint_dict = torch.load(path)
  File "/home/martin/anaconda3/envs/pytracking10/lib/python3.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/martin/anaconda3/envs/pytracking10/lib/python3.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by shashikant-ghangare** [comment]
It seems that the error is related to some issues with Pytorch 1.0 and Python 3.7. You can find more details here: https://github.com/pytorch/pytorch/issues/16203

**Comment by shashikant-ghangare** [comment]
I have tested with  Python 3.7 and it works fine.

**Comment by martin-danelljan** [comment]
Yes, the issue I had was unrelated. The network file did not download fully apparently. I will look into that.

This works great for me as well. Tested both tracking and training. I have not yet verified that the results stay the same though.

Thanks a lot for the contribution!

**Pull request merged**
